language: c
compiler: gcc
install:
  - sudo apt-get update
  - sudo apt-get install build-essential kernel-package bzip2 zip curl gcc-multilib libz-dev libc6:i386 libgcc1:i386 gcc-4.6-base:i386 libstdc++5:i386 libstdc++6:i386 lib32z1 libreadline6-dev:i386 libncurses5-dev:i386
  - mkdir ../Packages
  - mkdir ../Packages/KTweaker
  - mkdir ../linaro4.7
  - wget http://releases.linaro.org/13.01/components/android/toolchain/4.7/android-toolchain-eabi-linaro-4.7-2013.01-1-2013-01-17_01-27-05-linux-x86.tar.bz2
  - sudo tar -jxvf android-toolchain-eabi-linaro-4.7-2013.01-1-2013-01-17_01-27-05-linux-x86.tar.bz2
  - sudo mv android-toolchain-eabi linaro4.7
  - sudo mv linaro4.7 /home/travis/build/mikejr83/
  - ls -lh /home/travis/build/mikejr83/linaro4.7
  - ls -lh /home/travis/build/mikejr83/linaro4.7/bin
# Change this to your needs
script: ./Build_d2vzw.sh
